### ISSUE TITLE
Dev-ratio is still a bit of an issue 

### ISSUE THREAD

**Issue by SpiritBaker** [stackpoint/Dev-Click#2]
![devratio1](https://user-images.githubusercontent.com/34450337/87699061-1fd13100-c7b6-11ea-9604-b111402f265e.png)
![devratio2](https://user-images.githubusercontent.com/34450337/87699073-252e7b80-c7b6-11ea-949d-aa640bc2fefb.png)

**Comment by stackpoint** [comment]
There are two possible solutions:

- Have the AI dev adm/mil before if the dev-ratio is not correct (uses adm/mil points)
- Have the AI skip considering provinces that don't have correct dev-ratio (can run out of possible provinces)

**Comment by SpiritBaker** [comment]
I think it needs to be the second option.

**Comment by stackpoint** [comment]
What to do if all owned provinces don't have correct dev-ratio?

**Comment by SpiritBaker** [comment]
mercantilism? Better than nothing. That brings a question if there is a cap on mercantilism?

**Comment by stackpoint** [comment]
Caps at 100% I believe. 

![image](https://user-images.githubusercontent.com/5704491/87708331-40f63b00-c73e-11ea-9804-6595d349737e.png)

**Comment by SpiritBaker** [comment]
Yes it caps at 100%. Still this is a huge points sink. Typical AI is at 10-15% Mercantilism. So it's 100x85=8500 on average.

**Comment by stackpoint** [comment]
Okay, should be relatively simple to add.

**Comment by stackpoint** [comment]
Fixed here: https://github.com/stackpoint/Dev-Click/commit/fbed7bf748669c11d1d6d274e3102bd7237b275d
